sudo: required
services:
  - docker

before_install:
  - docker build -t Fizicallus/testdocker-react -f Dockerfile.dev .

script:
  - docker run Fizicallus/testdocker-react npm run test -- -- coverage
